/// Hive Types
const int HIVE_TYPE_ID_OVERVIEW_LIST_VO = 1;
const int HIVE_TYPE_ID_BOOK_VO = 2;
const int HIVE_TYPE_ID_BUY_LINK_VO = 3;
const int HIVE_TYPE_ID_ISBNS_VO = 4;
const int HIVE_TYPE_ID_REVIEW_VO = 5;
const int HIVE_TYPE_ID_SHELF_VO = 6;


/// Box Names
const String BOX_NAME_SAVE_BOOKS_VO = "BOX_NAME_SAVE_BOOKS_VO";
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BOOK_LIST_VO = "BOX_NAME_BOOK_LIST_VO";
const String BOX_NAME_SHELF_VO = "BOX_NAME_SHELF_VO";